In [1]:
# Libraries

from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.gaussian_process.kernels import RBF
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.decomposition import PCA
from sklearn import preprocessing
import matplotlib.pyplot as plt
from pandas import get_dummies
from sklearn import datasets
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib
import sklearn
import csv
import os

from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import  RadiusNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.svm import SVC
from sklearn.svm import NuSVC
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import ExtraTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

os.chdir("C:/titanic")

plt.style.use('ggplot')

%matplotlib inline

In [60]:
# Data upload

DF = pd.read_csv('train1.csv', sep=",", header=0, index_col=False)
DF = DF.drop(['PassengerId.1'], axis='columns')
DF.head()

   PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare
0            1         0       3    0  22.0      1      0   7.2500
1            2         1       1    1  38.0      1      0  71.2833
2            3         1       3    1  26.0      0      0   7.9250
3            4         1       1    1  35.0      1      0  53.1000
4            5         0       3    0  35.0      0      0   8.0500

In [30]:
X = DF.drop(['Survived'], axis='columns').values
y = DF.iloc[:, 2-1].values
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [89]:
df = pd.read_csv('test1.csv', sep=",", header=0, index_col=False)
df = df.drop(['PassengerId.1'], axis='columns')
df = df.fillna(df.mean())
df

     PassengerId  Pclass  Sex       Age  SibSp  Parch      Fare
0            892       3    0  34.50000      0      0    7.8292
1            893       3    1  47.00000      1      0    7.0000
2            894       2    0  62.00000      0      0    9.6875
3            895       3    0  27.00000      0      0    8.6625
4            896       3    1  22.00000      1      1   12.2875
5            897       3    0  14.00000      0      0    9.2250
6            898       3    1  30.00000      0      0    7.6292
7            899       2    0  26.00000      1      1   29.0000
8            900       3    1  18.00000      0      0    7.2292
9            901       3    0  21.00000      2      0   24.1500
10           902       3    0  30.27259      0      0    7.8958
11           903       1    0  46.00000      0      0   26.0000
12           904       1    1  23.00000      1      0   82.2667
13           905       2    0  63.00000      1      0   26.0000
14           906       1    1  47.00000      1      0   61.1750
15           907       2    1  24.00000      1      0   27.7208
16           908       2    0  35.00000      0      0   12.3500
17           909       3    0  21.00000      0      0    7.2250
18           910       3    1  27.00000      1      0    7.9250
19           911       3    1  45.00000      0      0    7.2250
20           912       1    0  55.00000      1      0   59.4000
21           913       3    0   9.00000      0      1    3.1708
22           914       1    1  30.27259      0      0   31.6833
23           915       1    0  21.00000      0      1   61.3792
24           916       1    1  48.00000      1      3  262.3750
25           917       3    0  50.00000      1      0   14.5000
26           918       1    1  22.00000      0      1   61.9792
27           919       3    0  22.50000      0      0    7.2250
28           920       1    0  41.00000      0      0   30.5000
29           921       3    0  30.27259      2      0   21.6792
..           ...     ...  ...       ...    ...    ...       ...
388         1280       3    0  21.00000      0      0    7.7500
389         1281       3    0   6.00000      3      1   21.0750
390         1282       1    0  23.00000      0      0   93.5000
391         1283       1    1  51.00000      0      1   39.4000
392         1284       3    0  13.00000      0      2   20.2500
393         1285       2    0  47.00000      0      0   10.5000
394         1286       3    0  29.00000      3      1   22.0250
395         1287       1    1  18.00000      1      0   60.0000
396         1288       3    0  24.00000      0      0    7.2500
397         1289       1    1  48.00000      1      1   79.2000
398         1290       3    0  22.00000      0      0    7.7750
399         1291       3    0  31.00000      0      0    7.7333
400         1292       1    1  30.00000      0      0  164.8667
401         1293       2    0  38.00000      1      0   21.0000
402         1294       1    1  22.00000      0      1   59.4000
403         1295       1    0  17.00000      0      0   47.1000
404         1296       1    0  43.00000      1      0   27.7208
405         1297       2    0  20.00000      0      0   13.8625
406         1298       2    0  23.00000      1      0   10.5000
407         1299       1    0  50.00000      1      1  211.5000
408         1300       3    1  30.27259      0      0    7.7208
409         1301       3    1   3.00000      1      1   13.7750
410         1302       3    1  30.27259      0      0    7.7500
411         1303       1    1  37.00000      1      0   90.0000
412         1304       3    1  28.00000      0      0    7.7750
413         1305       3    0  30.27259      0      0    8.0500
414         1306       1    1  39.00000      0      0  108.9000
415         1307       3    0  38.50000      0      0    7.2500
416         1308       3    0  30.27259      0      0    8.0500
417         1309       3    0  30.27259      1      1   22.3583

[418 rows x 7 columns]

In [90]:
X_test = df.values

# K-Nearest Neighbours

In [32]:
Model = KNeighborsClassifier(n_neighbors=8)
Model.fit(X, y)

y_pred = Model.predict(X)

print(classification_report(y, y_pred))
print(confusion_matrix(y, y_pred))
print('accuracy is',accuracy_score(y_pred, y))

             precision    recall  f1-score   support

          0       0.69      0.93      0.79       424
          1       0.80      0.39      0.53       290

avg / total       0.73      0.71      0.69       714

[[395  29]
 [176 114]]
accuracy is 0.7128851540616247

# Radius Neighbors Classifier

In [64]:
Model=RadiusNeighborsClassifier(radius=8.0)
Model.fit(X_train,y_train)

y_pred=Model.predict(X_test)

print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print('accuracy is ', accuracy_score(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00         6

    avg / total       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
accuracy is  1.0

# LogisticRegression

In [65]:
Model = LogisticRegression()
Model.fit(X_train, y_train)

y_pred = Model.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print('accuracy is',accuracy_score(y_pred,y_test))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      0.85      0.92        13
 Iris-virginica       0.75      1.00      0.86         6

    avg / total       0.95      0.93      0.94        30

[[11  0  0]
 [ 0 11  2]
 [ 0  0  6]]
accuracy is 0.9333333333333333

# Passive Aggressive Classifier

In [66]:
Model = PassiveAggressiveClassifier()
Model.fit(X_train, y_train)

y_pred = Model.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print('accuracy is',accuracy_score(y_pred,y_test))

                 precision    recall  f1-score   support

    Iris-setosa       0.52      1.00      0.69        11
Iris-versicolor       0.00      0.00      0.00        13
 Iris-virginica       0.67      1.00      0.80         6

    avg / total       0.33      0.57      0.41        30

[[11  0  0]
 [10  0  3]
 [ 0  0  6]]
accuracy is 0.5666666666666667

C:\Users\PRINT\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.passive_aggressive.PassiveAggressiveClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
C:\Users\PRINT\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

# Naive Bayes

In [67]:
Model = GaussianNB()
Model.fit(X_train, y_train)

y_pred = Model.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print('accuracy is',accuracy_score(y_pred,y_test))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00         6

    avg / total       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
accuracy is 1.0

# BernoulliNB

In [68]:
Model = BernoulliNB()
Model.fit(X_train, y_train)

y_pred = Model.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print('accuracy is',accuracy_score(y_pred,y_test))

                 precision    recall  f1-score   support

    Iris-setosa       0.00      0.00      0.00        11
Iris-versicolor       0.00      0.00      0.00        13
 Iris-virginica       0.20      1.00      0.33         6

    avg / total       0.04      0.20      0.07        30

[[ 0  0 11]
 [ 0  0 13]
 [ 0  0  6]]
accuracy is 0.2

C:\Users\PRINT\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

# Support Vector Machine

In [69]:
Model = SVC()
Model.fit(X_train, y_train)

y_pred = Model.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print('accuracy is',accuracy_score(y_pred,y_test))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00         6

    avg / total       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
accuracy is 1.0

# Support Vector Machine's

In [70]:
Model = NuSVC(nu=0.5)
Model.fit(X_train, y_train)

y_pred = Model.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print('accuracy is',accuracy_score(y_pred,y_test))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00         6

    avg / total       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
accuracy is 1.0

# Linear Support Vector Classification

In [71]:
Model = LinearSVC()
Model.fit(X_train, y_train)

y_pred = Model.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print('accuracy is',accuracy_score(y_pred,y_test))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.68      1.00      0.81        13
 Iris-virginica       0.00      0.00      0.00         6

    avg / total       0.66      0.80      0.72        30

[[11  0  0]
 [ 0 13  0]
 [ 0  6  0]]
accuracy is 0.8

C:\Users\PRINT\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

# Decision Tree's

In [33]:
Model = DecisionTreeClassifier()

Model.fit(X, y)

y_pred = Model.predict(X)

print(classification_report(y, y_pred))
print(confusion_matrix(y, y_pred))
print('accuracy is',accuracy_score(y_pred, y))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00       424
          1       1.00      1.00      1.00       290

avg / total       1.00      1.00      1.00       714

[[424   0]
 [  0 290]]
accuracy is 1.0

# ExtraTreeClassifier

In [73]:
Model = ExtraTreeClassifier()

Model.fit(X_train, y_train)

y_pred = Model.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print('accuracy is',accuracy_score(y_pred,y_test))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00         6

    avg / total       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
accuracy is 1.0

# Multi-layer Perceptron classifier

In [34]:
Model=MLPClassifier()

Model.fit(X, y)

y_pred=Model.predict(X)

print(classification_report(y, y_pred))
print(confusion_matrix(y, y_pred))
print('accuracy is ',accuracy_score(y_pred, y))

             precision    recall  f1-score   support

          0       0.76      0.66      0.71       424
          1       0.58      0.70      0.64       290

avg / total       0.69      0.68      0.68       714

[[279 145]
 [ 86 204]]
accuracy is  0.6764705882352942

# Random Forest

In [97]:
Model=RandomForestClassifier(max_depth=2)

Model.fit(X, y)

y_pred=Model.predict(X_test)

#print(classification_report(y, y_pred))
#print(confusion_matrix(y_pred, y))
#print('accuracy is ',accuracy_score(y_pred, y))

# Bagging classifier

In [76]:
Model=BaggingClassifier()

Model.fit(X_train,y_train)

y_pred=Model.predict(X_test)

print(classification_report(y_test,y_pred))
print(confusion_matrix(y_pred,y_test))
print('accuracy is ',accuracy_score(y_pred,y_test))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.93      1.00      0.96        13
 Iris-virginica       1.00      0.83      0.91         6

    avg / total       0.97      0.97      0.97        30

[[11  0  0]
 [ 0 13  1]
 [ 0  0  5]]
accuracy is  0.9666666666666667

# AdaBoost classifier

In [77]:
Model=AdaBoostClassifier()

Model.fit(X_train,y_train)

y_pred=Model.predict(X_test)

print(classification_report(y_test,y_pred))
print(confusion_matrix(y_pred,y_test))
print('accuracy is ',accuracy_score(y_pred,y_test))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.93      1.00      0.96        13
 Iris-virginica       1.00      0.83      0.91         6

    avg / total       0.97      0.97      0.97        30

[[11  0  0]
 [ 0 13  1]
 [ 0  0  5]]
accuracy is  0.9666666666666667

# Gradient Boosting Classifier

In [91]:
Model=GradientBoostingClassifier()

Model.fit(X, y)

y_pred=Model.predict(X_test)

#print(classification_report(y, y_pred))
#print(confusion_matrix(y_pred, y))
#print('accuracy is ',accuracy_score(y_pred, y))

In [68]:
y_pred

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0], dtype=int64)

# Linear Discriminant Analysis

In [79]:
Model=LinearDiscriminantAnalysis()

Model.fit(X_train,y_train)

y_pred=Model.predict(X_test)

print(classification_report(y_test,y_pred))
print(confusion_matrix(y_pred,y_test))
print('accuracy is ',accuracy_score(y_pred,y_test))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00         6

    avg / total       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
accuracy is  1.0

# Quadratic Discriminant Analysis

In [80]:
Model=QuadraticDiscriminantAnalysis()

Model.fit(X_train,y_train)

y_pred=Model.predict(X_test)

print(classification_report(y_test,y_pred))
print(confusion_matrix(y_pred,y_test))
print('accuracy is ',accuracy_score(y_pred,y_test))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00         6

    avg / total       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
accuracy is  1.0

In [62]:
DF = DF.drop(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare'], axis='columns')
#DF['SurvivedPrediction'] = pd.Series(y_pred.tolist())
Y = pd.Series(y_pred)

In [63]:
DF

     PassengerId  Survived
0              1         0
1              2         1
2              3         1
3              4         1
4              5         0
5              7         0
6              8         0
7              9         1
8             10         1
9             11         1
10            12         1
11            13         0
12            14         0
13            15         0
14            16         1
15            17         0
16            19         0
17            21         0
18            22         1
19            23         1
20            24         1
21            25         0
22            26         1
23            28         0
24            31         0
25            34         0
26            35         0
27            36         0
28            38         0
29            39         0
..           ...       ...
684          857         1
685          858         1
686          859         1
687          861         0
688          862         0
689          863         1
690          865         0
691          866         1
692          867         1
693          868         0
694          870         1
695          871         0
696          872         1
697          873         0
698          874         0
699          875         1
700          876         1
701          877         0
702          878         0
703          880         1
704          881         1
705          882         0
706          883         0
707          884         0
708          885         0
709          886         0
710          887         0
711          888         1
712          890         1
713          891         0

[714 rows x 2 columns]

In [64]:
DF['SurvivedPrediction'] = Y

In [65]:
DF

     PassengerId  Survived  SurvivedPrediction
0              1         0                   0
1              2         1                   1
2              3         1                   1
3              4         1                   1
4              5         0                   0
5              7         0                   0
6              8         0                   0
7              9         1                   1
8             10         1                   1
9             11         1                   1
10            12         1                   1
11            13         0                   0
12            14         0                   0
13            15         0                   0
14            16         1                   1
15            17         0                   0
16            19         0                   0
17            21         0                   0
18            22         1                   0
19            23         1                   1
20            24         1                   1
21            25         0                   0
22            26         1                   1
23            28         0                   0
24            31         0                   0
25            34         0                   0
26            35         0                   0
27            36         0                   0
28            38         0                   0
29            39         0                   0
..           ...       ...                 ...
684          857         1                   1
685          858         1                   0
686          859         1                   1
687          861         0                   0
688          862         0                   0
689          863         1                   1
690          865         0                   0
691          866         1                   1
692          867         1                   1
693          868         0                   0
694          870         1                   1
695          871         0                   0
696          872         1                   1
697          873         0                   0
698          874         0                   0
699          875         1                   1
700          876         1                   1
701          877         0                   0
702          878         0                   0
703          880         1                   1
704          881         1                   1
705          882         0                   0
706          883         0                   0
707          884         0                   0
708          885         0                   0
709          886         0                   0
710          887         0                   0
711          888         1                   1
712          890         1                   1
713          891         0                   0

[714 rows x 3 columns]

In [92]:
df = df.drop(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare'], axis='columns')

In [98]:
df['Survived'] = y_pred

In [100]:
df.to_csv('prediction_RF.csv', sep=',', index=False)

In [101]:
RF = pd.read_csv('prediction_RF.csv', sep=",", header=0, index_col=False)

In [102]:
RF

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
5            897         0
6            898         0
7            899         0
8            900         0
9            901         0
10           902         0
11           903         0
12           904         1
13           905         0
14           906         1
15           907         1
16           908         0
17           909         0
18           910         0
19           911         0
20           912         0
21           913         0
22           914         1
23           915         1
24           916         1
25           917         0
26           918         1
27           919         0
28           920         0
29           921         0
..           ...       ...
388         1280         0
389         1281         0
390         1282         0
391         1283         1
392         1284         0
393         1285         0
394         1286         0
395         1287         1
396         1288         0
397         1289         1
398         1290         0
399         1291         0
400         1292         1
401         1293         0
402         1294         1
403         1295         0
404         1296         0
405         1297         0
406         1298         0
407         1299         1
408         1300         0
409         1301         1
410         1302         0
411         1303         1
412         1304         0
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]